# ruff: noqa: F821
import numpy as np
indicator("Conditions pivot baseline")
i = np.arange(len(close))
source = ((i * 7) % 13 - 4).astype(float)
holes = np.where(np.isin(i, [1,7,8,12,23]), np.nan, source)
ties = ((i // 2) % 3).astype(float)
plot(when(ta.rising(source,1),1.0,0.0),'Rising 1')
plot(when(ta.falling(source,1),1.0,0.0),'Falling 1')
plot(when(ta.rising(source,3),1.0,0.0),'Rising 3')
plot(when(ta.falling(source,3),1.0,0.0),'Falling 3')
plot(when(ta.rising(holes,3),1.0,0.0),'Rising holes')
plot(when(ta.falling(holes,3),1.0,0.0),'Falling holes')
plot(ta.pivothigh(ties,2,2),'Pivot high ties')
plot(ta.pivotlow(ties,2,2),'Pivot low ties')
plot(ta.pivothigh(holes,2,2),'Pivot high holes')
plot(ta.pivotlow(holes,2,2),'Pivot low holes')
plot(ta.pivothigh(ties,0,2),'Pivot high 0 2')
plot(ta.pivotlow(ties,0,2),'Pivot low 0 2')
plot(ta.pivothigh(ties,2,0),'Pivot high 2 0')
plot(ta.pivotlow(ties,2,0),'Pivot low 2 0')
