# ruff: noqa: F821
import numpy as np
indicator("Context foundation")
i = np.arange(len(close))
volume_holes = np.where(np.isin(i, [1, 7, 8, 12, 23]), np.nan, volume)
plot(ta.adx(period=3), "ADX 3")
plot(ta.tr(), "True range")
plot(ta.obv(), "OBV")
plot(ta.volume_sma(period=3), "Volume SMA 3")
plot(ta.vwap(hlc3, i % 8 == 0), "VWAP anchor")
upper, middle, lower = ta.donchian(3)
plot(upper, "Donchian upper")
plot(middle, "Donchian middle")
plot(lower, "Donchian lower")
upper, middle, lower = ta.keltner(3, 1.5, width_smoothing="atr")
plot(upper, "Keltner upper")
plot(middle, "Keltner middle")
plot(lower, "Keltner lower")
plot(ta.obv(close, volume_holes), "OBV holes")
plot(ta.volume_sma(volume_holes, 3), "Volume SMA holes")
# Preserve the direct native KC comparison as well as the ATR-formula control.
upper, middle, lower = ta.keltner(3, 1.5)
plot(upper, "Native KC upper")
plot(middle, "Native KC middle")
plot(lower, "Native KC lower")
