# ruff: noqa: F821
indicator("EMA RSI boundaries")
leading = when(bar_index < 3, na, close)
holes = when((bar_index == 1) | (bar_index == 7) | (bar_index == 12), na, close)
plot(ta.ema(close, 3), "EMA")
plot(ta.ema(leading, 3), "EMA leading")
plot(ta.ema(holes, 3), "EMA holes")
macd, signal, histogram = ta.macd(holes, 2, 4, 3)
plot(macd, "MACD")
plot(signal, "Signal")
plot(histogram, "Histogram")
plot(ta.rsi(close * 0 + 10, 3), "RSI flat")
plot(ta.rsi(bar_index + 1, 3), "RSI rising")
plot(ta.rsi(100 - bar_index, 3), "RSI falling")
plot(ta.rsi(holes, 3), "RSI holes")
plot(ta.rsi(leading, 3), "RSI leading")
plot(ta.rsi(close, 3), "RSI base")
