# ruff: noqa: F821
import numpy as np
indicator("Extrema tie confirmation batch")
i = np.arange(len(close))
cycle = ((i // 3) % 2).astype(float)
gap = np.where(np.isin(i, [6, 7]) | ((i >= 18) & (i < 23)), np.nan, cycle)
flat = np.full(len(close), 5.0)
empty = np.full(len(close), np.nan)
plot(highest(gap, 1), 'Highest 1')
plot(lowest(gap, 1), 'Lowest 1')
plot(highestbars(gap, 1), 'Highestbars 1')
plot(lowestbars(gap, 1), 'Lowestbars 1')
plot(highest(gap, 5), 'Highest 5')
plot(lowest(gap, 5), 'Lowest 5')
plot(highestbars(gap, 5), 'Highestbars 5')
plot(lowestbars(gap, 5), 'Lowestbars 5')
plot(highestbars(flat, 3), 'Highestbars flat')
plot(lowestbars(flat, 3), 'Lowestbars flat')
plot(highest(empty, 3), 'Highest empty')
plot(lowest(empty, 3), 'Lowest empty')
plot(highestbars(empty, 3), 'Highestbars empty')
plot(lowestbars(empty, 3), 'Lowestbars empty')
