# ruff: noqa: F821
import numpy as np
indicator("Extrema boundaries batch")
i = np.arange(len(close))
source = ((i * 7) % 13 - 4).astype(float)
holes = np.where(np.isin(i, [1, 7, 8, 12]) | ((i >= 23) & (i <= 27)), np.nan, source)
ties = ((i // 2) % 3).astype(float)
leading = np.where(i < 5, np.nan, source)
plot(highest(holes, 3), 'Highest holes')
plot(lowest(holes, 3), 'Lowest holes')
plot(highestbars(holes, 3), 'Highestbars holes')
plot(lowestbars(holes, 3), 'Lowestbars holes')
plot(highest(ties, 3), 'Highest ties')
plot(lowest(ties, 3), 'Lowest ties')
plot(highestbars(ties, 3), 'Highestbars ties')
plot(lowestbars(ties, 3), 'Lowestbars ties')
plot(highest(leading, 3), 'Highest leading')
plot(lowest(leading, 3), 'Lowest leading')
plot(ta.linreg(holes, 3, 0), "Linreg holes")
plot(ta.percentile_nearest_rank(holes, 3, 50), "Nearest holes")
plot(ta.percentile_linear_interpolation(holes, 3, 50), "Linear holes")
