# ruff: noqa: F821
import numpy as np
indicator("Foundation missing boundaries")
i = np.arange(len(close))
source = ((i * 7) % 13 - 4).astype(float)
holes = np.where(np.isin(i, [1, 7, 8, 12, 23]), np.nan, source)
leading = np.where(i < 4, np.nan, source)
empty = np.full(len(close), np.nan)
other = ((i * 3) % 7 - 2).astype(float)
other_holes = np.where(np.isin(i, [2, 7, 13, 23]), np.nan, other)
zeros = np.where(i % 5 == 0, 0., source)
plot(ta.change(source, 1), "Change 1")
plot(ta.change(holes, 3), "Change holes 3")
plot(ta.mom(holes, 3), "Momentum holes 3")
plot(ta.roc(source, 1), "ROC 1")
plot(ta.roc(holes, 3), "ROC holes 3")
plot(ta.roc(zeros, 3), "ROC zeros 3")
plot(ta.cum(source), "Cum source")
plot(ta.cum(holes), "Cum holes")
plot(ta.cum(leading), "Cum leading")
plot(ta.cum(empty), "Cum empty")
plot(ta.nz(holes), "NZ holes")
plot(ta.nz(leading, 7), "NZ leading")
plot(ta.shift(holes, 3), "Shift holes 3")
plot(ta.shift(leading, 2), "Shift leading 2")
plot(when(ta.cross(source, other), 1., 0.), "Cross source")
plot(when(ta.cross(holes, other_holes), 1., 0.), "Cross holes")
plot(when(ta.crossunder(source, other), 1., 0.), "Crossunder source")
plot(when(ta.crossunder(holes, other_holes), 1., 0.), "Crossunder holes")
plot(when(ta.crossover(holes, other_holes), 1., 0.), "Crossover holes")
