# ruff: noqa: F821
import numpy as np
import pyne_runtime.ta as batch_ta

indicator("Percentile state generic Python replay", mode="incremental")


def init(ctx):
    ctx.state("history", [])
    # Disclose all-missing dynamic outputs to static result diagnostics.
    ctx.plot("Nearest holes 5 0", None)
    ctx.plot("Linear holes 5 0", None)
    ctx.plot("Nearest holes 5 12.5", None)
    ctx.plot("Linear holes 5 12.5", None)
    ctx.plot("Nearest holes 5 33", None)
    ctx.plot("Linear holes 5 33", None)
    ctx.plot("Nearest holes 5 50", None)
    ctx.plot("Linear holes 5 50", None)
    ctx.plot("Nearest holes 5 67", None)
    ctx.plot("Linear holes 5 67", None)
    ctx.plot("Nearest holes 5 87.5", None)
    ctx.plot("Linear holes 5 87.5", None)
    ctx.plot("Nearest holes 5 100", None)
    ctx.plot("Linear holes 5 100", None)
    ctx.plot("Nearest holes 9 0", None)
    ctx.plot("Linear holes 9 0", None)
    ctx.plot("Nearest holes 9 12.5", None)
    ctx.plot("Linear holes 9 12.5", None)
    ctx.plot("Nearest holes 9 33", None)
    ctx.plot("Linear holes 9 33", None)
    ctx.plot("Nearest holes 9 50", None)
    ctx.plot("Linear holes 9 50", None)
    ctx.plot("Nearest holes 9 67", None)
    ctx.plot("Linear holes 9 67", None)
    ctx.plot("Nearest holes 9 87.5", None)
    ctx.plot("Linear holes 9 87.5", None)
    ctx.plot("Nearest holes 9 100", None)
    ctx.plot("Linear holes 9 100", None)
    ctx.plot("Nearest holes 17 0", None)
    ctx.plot("Linear holes 17 0", None)
    ctx.plot("Nearest holes 17 12.5", None)
    ctx.plot("Linear holes 17 12.5", None)
    ctx.plot("Nearest holes 17 33", None)
    ctx.plot("Linear holes 17 33", None)
    ctx.plot("Nearest holes 17 50", None)
    ctx.plot("Linear holes 17 50", None)
    ctx.plot("Nearest holes 17 67", None)
    ctx.plot("Linear holes 17 67", None)
    ctx.plot("Nearest holes 17 87.5", None)
    ctx.plot("Linear holes 17 87.5", None)
    ctx.plot("Nearest holes 17 100", None)
    ctx.plot("Linear holes 17 100", None)
    ctx.plot("Nearest ties 5 0", None)
    ctx.plot("Linear ties 5 0", None)
    ctx.plot("Nearest ties 5 12.5", None)
    ctx.plot("Linear ties 5 12.5", None)
    ctx.plot("Nearest ties 5 33", None)
    ctx.plot("Linear ties 5 33", None)
    ctx.plot("Nearest ties 5 50", None)
    ctx.plot("Linear ties 5 50", None)
    ctx.plot("Nearest ties 5 67", None)
    ctx.plot("Linear ties 5 67", None)
    ctx.plot("Nearest ties 5 87.5", None)
    ctx.plot("Linear ties 5 87.5", None)
    ctx.plot("Nearest ties 5 100", None)
    ctx.plot("Linear ties 5 100", None)
    ctx.plot("Nearest ties 9 0", None)
    ctx.plot("Linear ties 9 0", None)
    ctx.plot("Nearest ties 9 12.5", None)
    ctx.plot("Linear ties 9 12.5", None)
    ctx.plot("Nearest ties 9 33", None)
    ctx.plot("Linear ties 9 33", None)
    ctx.plot("Nearest ties 9 50", None)
    ctx.plot("Linear ties 9 50", None)
    ctx.plot("Nearest ties 9 67", None)
    ctx.plot("Linear ties 9 67", None)
    ctx.plot("Nearest ties 9 87.5", None)
    ctx.plot("Linear ties 9 87.5", None)
    ctx.plot("Nearest ties 9 100", None)
    ctx.plot("Linear ties 9 100", None)
    ctx.plot("Nearest ties 17 0", None)
    ctx.plot("Linear ties 17 0", None)
    ctx.plot("Nearest ties 17 12.5", None)
    ctx.plot("Linear ties 17 12.5", None)
    ctx.plot("Nearest ties 17 33", None)
    ctx.plot("Linear ties 17 33", None)
    ctx.plot("Nearest ties 17 50", None)
    ctx.plot("Linear ties 17 50", None)
    ctx.plot("Nearest ties 17 67", None)
    ctx.plot("Linear ties 17 67", None)
    ctx.plot("Nearest ties 17 87.5", None)
    ctx.plot("Linear ties 17 87.5", None)
    ctx.plot("Nearest ties 17 100", None)
    ctx.plot("Linear ties 17 100", None)
    ctx.plot("Nearest leading 5 0", None)
    ctx.plot("Linear leading 5 0", None)
    ctx.plot("Nearest leading 5 12.5", None)
    ctx.plot("Linear leading 5 12.5", None)
    ctx.plot("Nearest leading 5 33", None)
    ctx.plot("Linear leading 5 33", None)
    ctx.plot("Nearest leading 5 50", None)
    ctx.plot("Linear leading 5 50", None)
    ctx.plot("Nearest leading 5 67", None)
    ctx.plot("Linear leading 5 67", None)
    ctx.plot("Nearest leading 5 87.5", None)
    ctx.plot("Linear leading 5 87.5", None)
    ctx.plot("Nearest leading 5 100", None)
    ctx.plot("Linear leading 5 100", None)
    ctx.plot("Nearest leading 9 0", None)
    ctx.plot("Linear leading 9 0", None)
    ctx.plot("Nearest leading 9 12.5", None)
    ctx.plot("Linear leading 9 12.5", None)
    ctx.plot("Nearest leading 9 33", None)
    ctx.plot("Linear leading 9 33", None)
    ctx.plot("Nearest leading 9 50", None)
    ctx.plot("Linear leading 9 50", None)
    ctx.plot("Nearest leading 9 67", None)
    ctx.plot("Linear leading 9 67", None)
    ctx.plot("Nearest leading 9 87.5", None)
    ctx.plot("Linear leading 9 87.5", None)
    ctx.plot("Nearest leading 9 100", None)
    ctx.plot("Linear leading 9 100", None)
    ctx.plot("Nearest leading 17 0", None)
    ctx.plot("Linear leading 17 0", None)
    ctx.plot("Nearest leading 17 12.5", None)
    ctx.plot("Linear leading 17 12.5", None)
    ctx.plot("Nearest leading 17 33", None)
    ctx.plot("Linear leading 17 33", None)
    ctx.plot("Nearest leading 17 50", None)
    ctx.plot("Linear leading 17 50", None)
    ctx.plot("Nearest leading 17 67", None)
    ctx.plot("Linear leading 17 67", None)
    ctx.plot("Nearest leading 17 87.5", None)
    ctx.plot("Linear leading 17 87.5", None)
    ctx.plot("Nearest leading 17 100", None)
    ctx.plot("Linear leading 17 100", None)
    ctx.plot("Nearest empty 5 0", None)
    ctx.plot("Linear empty 5 0", None)
    ctx.plot("Nearest empty 5 12.5", None)
    ctx.plot("Linear empty 5 12.5", None)
    ctx.plot("Nearest empty 5 33", None)
    ctx.plot("Linear empty 5 33", None)
    ctx.plot("Nearest empty 5 50", None)
    ctx.plot("Linear empty 5 50", None)
    ctx.plot("Nearest empty 5 67", None)
    ctx.plot("Linear empty 5 67", None)
    ctx.plot("Nearest empty 5 87.5", None)
    ctx.plot("Linear empty 5 87.5", None)
    ctx.plot("Nearest empty 5 100", None)
    ctx.plot("Linear empty 5 100", None)
    ctx.plot("Nearest empty 9 0", None)
    ctx.plot("Linear empty 9 0", None)
    ctx.plot("Nearest empty 9 12.5", None)
    ctx.plot("Linear empty 9 12.5", None)
    ctx.plot("Nearest empty 9 33", None)
    ctx.plot("Linear empty 9 33", None)
    ctx.plot("Nearest empty 9 50", None)
    ctx.plot("Linear empty 9 50", None)
    ctx.plot("Nearest empty 9 67", None)
    ctx.plot("Linear empty 9 67", None)
    ctx.plot("Nearest empty 9 87.5", None)
    ctx.plot("Linear empty 9 87.5", None)
    ctx.plot("Nearest empty 9 100", None)
    ctx.plot("Linear empty 9 100", None)
    ctx.plot("Nearest empty 17 0", None)
    ctx.plot("Linear empty 17 0", None)
    ctx.plot("Nearest empty 17 12.5", None)
    ctx.plot("Linear empty 17 12.5", None)
    ctx.plot("Nearest empty 17 33", None)
    ctx.plot("Linear empty 17 33", None)
    ctx.plot("Nearest empty 17 50", None)
    ctx.plot("Linear empty 17 50", None)
    ctx.plot("Nearest empty 17 67", None)
    ctx.plot("Linear empty 17 67", None)
    ctx.plot("Nearest empty 17 87.5", None)
    ctx.plot("Linear empty 17 87.5", None)
    ctx.plot("Nearest empty 17 100", None)
    ctx.plot("Linear empty 17 100", None)


def on_bar(ctx, bar):
    history = ctx.state("history").value
    history.append(bar.close)
    base = np.asarray(history, dtype=float)
    i = np.arange(len(base))
    sources = {
        "holes": np.where(np.isin(i % 11, (2, 3, 4)), np.nan, base),
        "ties": np.where(np.isin(i % 17, (7, 8)), np.nan, (i // 3) % 5 - 2).astype(float),
        "leading": np.where((i < 13) | ((i >= 45) & (i < 58)), np.nan, base),
        "empty": np.full(len(base), np.nan),
    }
    module = batch_ta.TaModule()
    for name, source in sources.items():
        for period in (5, 9, 17):
            for percentage in (0, 12.5, 33, 50, 67, 87.5, 100):
                suffix = f"{name} {period} {percentage:g}"
                ctx.plot("Nearest " + suffix, module.percentile_nearest_rank(source, period, percentage)[-1])
                ctx.plot("Linear " + suffix, module.percentile_linear_interpolation(source, period, percentage)[-1])
