# ruff: noqa: F821
indicator("Rolling statistics")
holes = when((bar_index == 1) | (bar_index == 7) | (bar_index == 12), na, close)
leading = when(bar_index < 3, na, close)
high_source = 1000000000.0 + holes
plot(ta.sma(close, 3), "SMA base")
plot(ta.sma(holes, 3), "SMA holes")
plot(ta.sma(leading, 3), "SMA leading")
plot(ta.stdev(holes, 3), "Stdev")
plot(ta.variance(holes, 3), "Variance")
plot(ta.variance(holes, 3, False), "Sample variance")
mid, upper, lower = ta.bb(holes, 3, 2)
plot(mid, "Middle")
plot(upper, "Upper")
plot(lower, "Lower")
plot(ta.sma(high_source, 3), "High SMA")
plot(ta.stdev(high_source, 3), "High Stdev")
plot(ta.variance(high_source, 3), "High Variance")
plot(ta.variance(holes, 1, False), "Sample variance 1")
plot(ta.sma(holes, 1), "SMA 1")
plot(ta.sma(when(bar_index >= 0, na, close), 3), "Empty SMA")
plot(ta.stdev(when(bar_index >= 0, na, close), 3), "Empty Stdev")
