# ruff: noqa: F821
import numpy as np
indicator("SMA independent holdout",mode="batch")
def inputs(i):
    base = float(i * 13 % 23 - 10) * 0.25
    power = 2.0 ** 80 + base * 2.0 ** 28
    return dict(base=base, offset=1000000000000.0 + base, power=power, prefill=power if i < 13 else base, negative=-power if i < 13 else base, mixed=power if i % 4 == 0 else -power if i % 4 == 1 else base, holes=None if i >= 13 and i % 9 in (1, 4, 5) else power if i < 13 else base, leading=None if i < 5 else 1000000000000.0 + base, empty=None, singleGap=None if i == 17 else 1000000000000.0 + base if i < 25 else base, alternate=power if i % 2 == 0 else None, regime=power if i < 24 else base if i < 48 else -power if i < 72 else base)
rows = [inputs(index) for index in range(len(close))]
values = np.asarray([np.nan if row['base'] is None else row['base'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 base')
plot(ta.sma(values,3),'Native3 base')
values = np.asarray([np.nan if row['offset'] is None else row['offset'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 offset')
plot(ta.sma(values,3),'Native3 offset')
values = np.asarray([np.nan if row['power'] is None else row['power'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 power')
plot(ta.sma(values,3),'Native3 power')
values = np.asarray([np.nan if row['prefill'] is None else row['prefill'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 prefill')
plot(ta.sma(values,3),'Native3 prefill')
values = np.asarray([np.nan if row['negative'] is None else row['negative'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 negative')
plot(ta.sma(values,3),'Native3 negative')
values = np.asarray([np.nan if row['mixed'] is None else row['mixed'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 mixed')
plot(ta.sma(values,3),'Native3 mixed')
values = np.asarray([np.nan if row['holes'] is None else row['holes'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 holes')
plot(ta.sma(values,3),'Native3 holes')
values = np.asarray([np.nan if row['leading'] is None else row['leading'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 leading')
plot(ta.sma(values,3),'Native3 leading')
values = np.asarray([np.nan if row['empty'] is None else row['empty'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 empty')
plot(ta.sma(values,3),'Native3 empty')
values = np.asarray([np.nan if row['singleGap'] is None else row['singleGap'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 singleGap')
plot(ta.sma(values,3),'Native3 singleGap')
values = np.asarray([np.nan if row['alternate'] is None else row['alternate'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 alternate')
plot(ta.sma(values,3),'Native3 alternate')
values = np.asarray([np.nan if row['regime'] is None else row['regime'] for row in rows],dtype=np.float64)
plot(ta.sma(values,2),'Native2 regime')
plot(ta.sma(values,3),'Native3 regime')
