# ruff: noqa: F821
import numpy as np
strategy("Pyramiding 3", initial_capital=1000000000, pyramiding=3, process_orders_on_close=True, margin_long=0, margin_short=0)
strategy.entry('L0', strategy.long, qty=1, when=bar_index == 0, price=close)
strategy.entry('L1', strategy.long, qty=1, when=bar_index == 1, price=close)
strategy.entry('L2', strategy.long, qty=1, when=bar_index == 2, price=close)
strategy.entry('L3', strategy.long, qty=1, when=bar_index == 3, price=close)
strategy.entry('R', strategy.short, qty=2, when=bar_index == 4, price=close)
strategy.entry('S5', strategy.short, qty=1, when=bar_index == 5, price=close)
strategy.entry('S6', strategy.short, qty=1, when=bar_index == 6, price=close)
strategy.entry('S7', strategy.short, qty=1, when=bar_index == 7, price=close)
strategy.close_all(when=bar_index == 8, price=close)
strategy.entry('N9', strategy.long, qty=1, when=bar_index == 9, price=close)
strategy.entry('N10', strategy.long, qty=1, when=bar_index == 10, price=close)
strategy.entry('N11', strategy.long, qty=1, when=bar_index == 11, price=close)
strategy.entry('N12', strategy.long, qty=1, when=bar_index == 12, price=close)
strategy.order('Order', strategy.long, qty=3, when=bar_index == 13, price=close)
strategy.entry('Blocked14', strategy.long, qty=1, when=bar_index == 14, price=close)
strategy.close_all(when=bar_index == 15, price=close)
strategy.entry('Repeated', strategy.long, qty=0.5, when=bar_index == 16, price=close)
strategy.entry('Repeated', strategy.long, qty=0.5, when=bar_index == 17, price=close)
strategy.entry('Repeated', strategy.long, qty=0.5, when=bar_index == 18, price=close)
strategy.entry('Repeated', strategy.long, qty=0.5, when=bar_index == 19, price=close)
strategy.close('Repeated', qty=0.5, when=bar_index == 18, price=close)
strategy.close_all(when=bar_index == 20, price=close)
plot(strategy.position_size, 'Position')
plot(strategy.opentrades, 'Open trades')
plot(strategy.closedtrades, 'Closed trades')
plot(strategy.position_avg_price, 'Average')
plot(strategy.netprofit, 'Net profit')
count = int(np.max(np.asarray(strategy.opentrades.count)))
signed = np.where(np.asarray(strategy.position_size) < 0, -1.0, 1.0)
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [0]), size*signed, 0.0)
plot(quantity, 'Held L0')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [1]), size*signed, 0.0)
plot(quantity, 'Held L1')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [2]), size*signed, 0.0)
plot(quantity, 'Held L2')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [3]), size*signed, 0.0)
plot(quantity, 'Held L3')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [4]), size*signed, 0.0)
plot(quantity, 'Held R')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [5]), size*signed, 0.0)
plot(quantity, 'Held S5')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [6]), size*signed, 0.0)
plot(quantity, 'Held S6')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [7]), size*signed, 0.0)
plot(quantity, 'Held S7')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [9]), size*signed, 0.0)
plot(quantity, 'Held N9')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [10]), size*signed, 0.0)
plot(quantity, 'Held N10')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [11]), size*signed, 0.0)
plot(quantity, 'Held N11')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [12]), size*signed, 0.0)
plot(quantity, 'Held N12')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [13]), size*signed, 0.0)
plot(quantity, 'Held Order')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [14]), size*signed, 0.0)
plot(quantity, 'Held Blocked14')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [16, 17, 18, 19]), size*signed, 0.0)
plot(quantity, 'Held Repeated')
