# ruff: noqa: F821
import numpy as np
strategy("Pyramiding 2", initial_capital=1000000000, pyramiding=2, process_orders_on_close=True, margin_long=0, margin_short=0)
strategy.entry('A', strategy.long, qty=1, when=bar_index == 0, price=close)
strategy.order('B', strategy.long, qty=2, when=bar_index == 1, price=close)
strategy.entry('C', strategy.long, qty=1, when=bar_index == 2, price=close)
strategy.entry('D', strategy.long, qty=1, when=bar_index == 3, price=close)
strategy.close('A', when=bar_index == 4, price=close)
strategy.entry('E', strategy.long, qty=1, when=bar_index == 5, price=close)
strategy.close('B', when=bar_index == 6, price=close)
strategy.entry('F', strategy.long, qty=1, when=bar_index == 7, price=close)
strategy.close_all(when=bar_index == 8, price=close)
strategy.order('G', strategy.long, qty=1, when=bar_index == 9, price=close)
strategy.entry('H', strategy.long, qty=1, when=bar_index == 10, price=close)
strategy.order('I', strategy.long, qty=1, when=bar_index == 11, price=close)
strategy.entry('J', strategy.long, qty=1, when=bar_index == 12, price=close)
strategy.close_all(when=bar_index == 13, price=close)
plot(strategy.position_size, 'Position')
plot(strategy.opentrades, 'Open trades')
plot(strategy.closedtrades, 'Closed trades')
plot(strategy.position_avg_price, 'Average')
plot(strategy.netprofit, 'Net profit')
count = int(np.max(np.asarray(strategy.opentrades.count)))
signed = np.where(np.asarray(strategy.position_size) < 0, -1.0, 1.0)
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [0]), size*signed, 0.0)
plot(quantity, 'Held A')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [1]), size*signed, 0.0)
plot(quantity, 'Held B')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [2]), size*signed, 0.0)
plot(quantity, 'Held C')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [3]), size*signed, 0.0)
plot(quantity, 'Held D')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [5]), size*signed, 0.0)
plot(quantity, 'Held E')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [7]), size*signed, 0.0)
plot(quantity, 'Held F')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [9]), size*signed, 0.0)
plot(quantity, 'Held G')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [10]), size*signed, 0.0)
plot(quantity, 'Held H')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [11]), size*signed, 0.0)
plot(quantity, 'Held I')
quantity = np.zeros(len(close))
for j in range(count):
    entry_index = np.asarray(strategy.opentrades.entry_bar_index(j))
    size = np.nan_to_num(np.asarray(strategy.opentrades.size(j)), nan=0.0)
    quantity += np.where(np.isin(entry_index, [12]), size*signed, 0.0)
plot(quantity, 'Held J')
