# ruff: noqa: F821
indicator("Trend volume boundaries")
src = 10.0 * (bar_index % 4 + 1)
holes = when((bar_index == 1) | (bar_index == 7) | (bar_index == 12), na, src)
leading = when(bar_index < 3, na, src)
weights = bar_index % 3 + 1.0
missing_weights = when((bar_index == 2) | (bar_index == 9), na, weights)
st, direction = ta.supertrend(2.0, 3)
st1, direction1 = ta.supertrend(2.0, 1)
plot(st, "ST 3")
plot(direction, "Direction 3")
plot(st1, "ST 1")
plot(direction1, "Direction 1")
plot(ta.atr(3), "ATR 3")
plot(ta.vwma(close, 3), "VWMA close")
plot(ta.vwma(holes, 3), "VWMA holes")
plot(ta.vwma(leading, 3), "VWMA leading")
plot(ta.vwma(holes, 3, weights), "Custom price holes")
plot(ta.vwma(src, 3, missing_weights), "Custom volume holes")
plot(ta.vwma(holes, 3, missing_weights), "Custom both holes")
plot(ta.vwma(src, 3, close * 0), "Zero weight")
