# ruff: noqa: F821
import numpy as np
indicator("Window readiness holdout batch")
def sources(i):
    base = float(((i // 3) * 7) % 13 - 4)
    return dict(base=base, holes=None if i == 1 or 6 <= i <= 9 or 23 <= i <= 30 else base,
                leading=None if i < 8 else base, flat=5., missing=None)

values = {key: np.asarray([sources(i)[key] for i in range(len(close))], dtype=float)
          for key in sources(0)}
plot(ta.highest(values['base'], 1), 'highest base 1')
plot(ta.lowest(values['base'], 1), 'lowest base 1')
plot(ta.highestbars(values['base'], 1), 'highestbars base 1')
plot(ta.lowestbars(values['base'], 1), 'lowestbars base 1')
plot(ta.stoch(values['base'], values['base'] + 1, values['base'] - 1, 1), 'stoch base 1')
plot(ta.highest(values['base'], 2), 'highest base 2')
plot(ta.lowest(values['base'], 2), 'lowest base 2')
plot(ta.highestbars(values['base'], 2), 'highestbars base 2')
plot(ta.lowestbars(values['base'], 2), 'lowestbars base 2')
plot(ta.stoch(values['base'], values['base'] + 1, values['base'] - 1, 2), 'stoch base 2')
plot(ta.highest(values['base'], 3), 'highest base 3')
plot(ta.lowest(values['base'], 3), 'lowest base 3')
plot(ta.highestbars(values['base'], 3), 'highestbars base 3')
plot(ta.lowestbars(values['base'], 3), 'lowestbars base 3')
plot(ta.stoch(values['base'], values['base'] + 1, values['base'] - 1, 3), 'stoch base 3')
plot(ta.highest(values['base'], 5), 'highest base 5')
plot(ta.lowest(values['base'], 5), 'lowest base 5')
plot(ta.highestbars(values['base'], 5), 'highestbars base 5')
plot(ta.lowestbars(values['base'], 5), 'lowestbars base 5')
plot(ta.stoch(values['base'], values['base'] + 1, values['base'] - 1, 5), 'stoch base 5')
plot(ta.highest(values['base'], 11), 'highest base 11')
plot(ta.lowest(values['base'], 11), 'lowest base 11')
plot(ta.highestbars(values['base'], 11), 'highestbars base 11')
plot(ta.lowestbars(values['base'], 11), 'lowestbars base 11')
plot(ta.stoch(values['base'], values['base'] + 1, values['base'] - 1, 11), 'stoch base 11')
plot(ta.highest(values['holes'], 1), 'highest holes 1')
plot(ta.lowest(values['holes'], 1), 'lowest holes 1')
plot(ta.highestbars(values['holes'], 1), 'highestbars holes 1')
plot(ta.lowestbars(values['holes'], 1), 'lowestbars holes 1')
plot(ta.stoch(values['holes'], values['holes'] + 1, values['holes'] - 1, 1), 'stoch holes 1')
plot(ta.highest(values['holes'], 2), 'highest holes 2')
plot(ta.lowest(values['holes'], 2), 'lowest holes 2')
plot(ta.highestbars(values['holes'], 2), 'highestbars holes 2')
plot(ta.lowestbars(values['holes'], 2), 'lowestbars holes 2')
plot(ta.stoch(values['holes'], values['holes'] + 1, values['holes'] - 1, 2), 'stoch holes 2')
plot(ta.highest(values['holes'], 3), 'highest holes 3')
plot(ta.lowest(values['holes'], 3), 'lowest holes 3')
plot(ta.highestbars(values['holes'], 3), 'highestbars holes 3')
plot(ta.lowestbars(values['holes'], 3), 'lowestbars holes 3')
plot(ta.stoch(values['holes'], values['holes'] + 1, values['holes'] - 1, 3), 'stoch holes 3')
plot(ta.highest(values['holes'], 5), 'highest holes 5')
plot(ta.lowest(values['holes'], 5), 'lowest holes 5')
plot(ta.highestbars(values['holes'], 5), 'highestbars holes 5')
plot(ta.lowestbars(values['holes'], 5), 'lowestbars holes 5')
plot(ta.stoch(values['holes'], values['holes'] + 1, values['holes'] - 1, 5), 'stoch holes 5')
plot(ta.highest(values['holes'], 11), 'highest holes 11')
plot(ta.lowest(values['holes'], 11), 'lowest holes 11')
plot(ta.highestbars(values['holes'], 11), 'highestbars holes 11')
plot(ta.lowestbars(values['holes'], 11), 'lowestbars holes 11')
plot(ta.stoch(values['holes'], values['holes'] + 1, values['holes'] - 1, 11), 'stoch holes 11')
plot(ta.highest(values['leading'], 1), 'highest leading 1')
plot(ta.lowest(values['leading'], 1), 'lowest leading 1')
plot(ta.highestbars(values['leading'], 1), 'highestbars leading 1')
plot(ta.lowestbars(values['leading'], 1), 'lowestbars leading 1')
plot(ta.stoch(values['leading'], values['leading'] + 1, values['leading'] - 1, 1), 'stoch leading 1')
plot(ta.highest(values['leading'], 2), 'highest leading 2')
plot(ta.lowest(values['leading'], 2), 'lowest leading 2')
plot(ta.highestbars(values['leading'], 2), 'highestbars leading 2')
plot(ta.lowestbars(values['leading'], 2), 'lowestbars leading 2')
plot(ta.stoch(values['leading'], values['leading'] + 1, values['leading'] - 1, 2), 'stoch leading 2')
plot(ta.highest(values['leading'], 3), 'highest leading 3')
plot(ta.lowest(values['leading'], 3), 'lowest leading 3')
plot(ta.highestbars(values['leading'], 3), 'highestbars leading 3')
plot(ta.lowestbars(values['leading'], 3), 'lowestbars leading 3')
plot(ta.stoch(values['leading'], values['leading'] + 1, values['leading'] - 1, 3), 'stoch leading 3')
plot(ta.highest(values['leading'], 5), 'highest leading 5')
plot(ta.lowest(values['leading'], 5), 'lowest leading 5')
plot(ta.highestbars(values['leading'], 5), 'highestbars leading 5')
plot(ta.lowestbars(values['leading'], 5), 'lowestbars leading 5')
plot(ta.stoch(values['leading'], values['leading'] + 1, values['leading'] - 1, 5), 'stoch leading 5')
plot(ta.highest(values['leading'], 11), 'highest leading 11')
plot(ta.lowest(values['leading'], 11), 'lowest leading 11')
plot(ta.highestbars(values['leading'], 11), 'highestbars leading 11')
plot(ta.lowestbars(values['leading'], 11), 'lowestbars leading 11')
plot(ta.stoch(values['leading'], values['leading'] + 1, values['leading'] - 1, 11), 'stoch leading 11')
plot(ta.highest(values['flat'], 1), 'highest flat 1')
plot(ta.lowest(values['flat'], 1), 'lowest flat 1')
plot(ta.highestbars(values['flat'], 1), 'highestbars flat 1')
plot(ta.lowestbars(values['flat'], 1), 'lowestbars flat 1')
plot(ta.stoch(values['flat'], values['flat'], values['flat'], 1), 'stoch flat 1')
plot(ta.highest(values['flat'], 2), 'highest flat 2')
plot(ta.lowest(values['flat'], 2), 'lowest flat 2')
plot(ta.highestbars(values['flat'], 2), 'highestbars flat 2')
plot(ta.lowestbars(values['flat'], 2), 'lowestbars flat 2')
plot(ta.stoch(values['flat'], values['flat'], values['flat'], 2), 'stoch flat 2')
plot(ta.highest(values['flat'], 3), 'highest flat 3')
plot(ta.lowest(values['flat'], 3), 'lowest flat 3')
plot(ta.highestbars(values['flat'], 3), 'highestbars flat 3')
plot(ta.lowestbars(values['flat'], 3), 'lowestbars flat 3')
plot(ta.stoch(values['flat'], values['flat'], values['flat'], 3), 'stoch flat 3')
plot(ta.highest(values['flat'], 5), 'highest flat 5')
plot(ta.lowest(values['flat'], 5), 'lowest flat 5')
plot(ta.highestbars(values['flat'], 5), 'highestbars flat 5')
plot(ta.lowestbars(values['flat'], 5), 'lowestbars flat 5')
plot(ta.stoch(values['flat'], values['flat'], values['flat'], 5), 'stoch flat 5')
plot(ta.highest(values['flat'], 11), 'highest flat 11')
plot(ta.lowest(values['flat'], 11), 'lowest flat 11')
plot(ta.highestbars(values['flat'], 11), 'highestbars flat 11')
plot(ta.lowestbars(values['flat'], 11), 'lowestbars flat 11')
plot(ta.stoch(values['flat'], values['flat'], values['flat'], 11), 'stoch flat 11')
plot(ta.highest(values['missing'], 1), 'highest missing 1')
plot(ta.lowest(values['missing'], 1), 'lowest missing 1')
plot(ta.highestbars(values['missing'], 1), 'highestbars missing 1')
plot(ta.lowestbars(values['missing'], 1), 'lowestbars missing 1')
plot(ta.stoch(values['missing'], values['missing'] + 1, values['missing'] - 1, 1), 'stoch missing 1')
plot(ta.highest(values['missing'], 2), 'highest missing 2')
plot(ta.lowest(values['missing'], 2), 'lowest missing 2')
plot(ta.highestbars(values['missing'], 2), 'highestbars missing 2')
plot(ta.lowestbars(values['missing'], 2), 'lowestbars missing 2')
plot(ta.stoch(values['missing'], values['missing'] + 1, values['missing'] - 1, 2), 'stoch missing 2')
plot(ta.highest(values['missing'], 3), 'highest missing 3')
plot(ta.lowest(values['missing'], 3), 'lowest missing 3')
plot(ta.highestbars(values['missing'], 3), 'highestbars missing 3')
plot(ta.lowestbars(values['missing'], 3), 'lowestbars missing 3')
plot(ta.stoch(values['missing'], values['missing'] + 1, values['missing'] - 1, 3), 'stoch missing 3')
plot(ta.highest(values['missing'], 5), 'highest missing 5')
plot(ta.lowest(values['missing'], 5), 'lowest missing 5')
plot(ta.highestbars(values['missing'], 5), 'highestbars missing 5')
plot(ta.lowestbars(values['missing'], 5), 'lowestbars missing 5')
plot(ta.stoch(values['missing'], values['missing'] + 1, values['missing'] - 1, 5), 'stoch missing 5')
plot(ta.highest(values['missing'], 11), 'highest missing 11')
plot(ta.lowest(values['missing'], 11), 'lowest missing 11')
plot(ta.highestbars(values['missing'], 11), 'highestbars missing 11')
plot(ta.lowestbars(values['missing'], 11), 'lowestbars missing 11')
plot(ta.stoch(values['missing'], values['missing'] + 1, values['missing'] - 1, 11), 'stoch missing 11')
